server:
  port: 8769

stores:
  ribbon:
    listOfServers: baidu.com,google.com
ribbon:
  eureka:
    enabled: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/



