

turbine:
  aggregator:
    clusterConfig: default
  appConfig: eureka-ribbon-client,eureka-feign-client
  clusterNameExpression: new String("default")

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: service-turbine
server:
  port: 8769